{{- if .Values.secretProviderClass.enabled }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.applicationName }}-spc
  namespace: {{ .Values.namespace}}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.kvUAMI }}
    keyvaultName: {{ .Values.kvName }}
    cloudName: ""
    objects: |
    {{- .Values.secretProviderClass.objects | nindent 6 }}
    tenantId: {{ .Values.kvTenantId }}
{{- end }}