apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-hub
spec:
  provider: azure
  secretObjects:
    - secretName: nginx-default-tls
      type: kubernetes.io/tls
      data:
        - objectName: cert
          key: tls.key
        - objectName: cert
          key: tls.crt
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: xxxxxx
    keyvaultName: xxxxxxxx
    cloudName: ""
    objects: |
      array:
        - |
          objectName: cert
          objectType: secret
    tenantId: xxxxxxxxx